apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n32i4fqlw-dotnet-basic
  janus-idp.io/tekton: n32i4fqlw-dotnet-basic
  backstage.io/kubernetes-id: n32i4fqlw-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n32i4fqlw-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
